#!/bin/bash
# Generated Shell Telemetry Constants for SWARMSH v2
# DO NOT EDIT - Generated by OTEL Weaver

# Agent constants
export SWARMSH_AGENT_ID="swarmsh.agent.id"
export SWARMSH_AGENT_ROLE="swarmsh.agent.role"
export SWARMSH_AGENT_STATUS="swarmsh.agent.status"
export SWARMSH_AGENT_CAPACITY="swarmsh.agent.capacity"

# Coordination constants
export SWARMSH_COORDINATION_PATTERN="swarmsh.coordination.pattern"
export SWARMSH_COORDINATION_EPOCH="swarmsh.coordination.epoch"
export SWARMSH_COORDINATION_PARTICIPANT_COUNT="swarmsh.coordination.participant_count"

# Work constants
export SWARMSH_WORK_ID="swarmsh.work.id"
export SWARMSH_WORK_STATUS="swarmsh.work.status"
export SWARMSH_WORK_PRIORITY="swarmsh.work.priority"

# Helper functions
nano_id() {
    local prefix="${1:-item}"
    echo "${prefix}_$(date +%s%N)"
}

otel_attr() {
    local key="$1"
    local value="$2"
    echo "\"${key}=${value}\""
}
