//! Agent coordination engine for SwarmSH v2.
//!
//! The coordination layer provides bounded in-process atomicity for agent
//! registration and work claiming. External AI analysis is optional and is
//! deliberately kept outside coordination critical sections.

use crate::ai_integration::{AIAnalysis, AIIntegration};
use crate::telemetry::{CorrelationId, DefaultSwarmTelemetry, PerfTimer, SwarmTelemetry};
use crate::{AgentId, SwarmError, SwarmResult, WorkId};
use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};
use std::cmp::Ordering;
use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Instant, SystemTime, UNIX_EPOCH};
use tokio::sync::{Mutex, RwLock};
use tokio_stream::StreamExt;
use tracing::{debug, info, instrument, warn};

/// Coordination patterns supported by SwarmSH.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum CoordinationPattern {
    /// Scrum at Scale coordination.
    ScrumAtScale,
    /// Roberts Rules governance and decision making.
    RobertsRules,
    /// Real-time coordination for high-frequency operations.
    Realtime,
    /// In-process atomic coordination.
    Atomic,
}

impl CoordinationPattern {
    /// Get the bounded behavior represented by this pattern.
    pub fn description(&self) -> &str {
        match self {
            Self::ScrumAtScale => {
                "Scrum at Scale coordination with sprint-based cycles and team synchronization"
            }
            Self::RobertsRules => "Roberts Rules governance for formal decision making and voting",
            Self::Realtime => "Real-time coordination with bounded in-process state snapshots",
            Self::Atomic => "Atomic in-process coordination using Tokio synchronization primitives",
        }
    }
}

/// Trait for agent patterns generated by meta-programming macros.
pub trait AgentPattern {
    fn agent_id(&self) -> &AgentId;
    fn role(&self) -> &str;
    fn capacity(&self) -> f64;
    fn coordination_patterns(&self) -> &[&str];
}

/// Agent specification for registration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentSpec {
    pub id: AgentId,
    pub role: String,
    pub capacity: f64,
    pub specializations: Vec<String>,
    pub work_capacity: Option<u32>,
}

/// Agent state tracking.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentState {
    pub spec: AgentSpec,
    pub status: AgentStatus,
    pub current_work: Option<WorkId>,
    pub last_heartbeat: SystemTime,
    pub performance_metrics: AgentMetrics,
}

/// Agent status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AgentStatus {
    Active,
    Idle,
    Working,
    Blocked,
    Failed,
}

/// Agent performance metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentMetrics {
    pub work_completed: u64,
    pub average_completion_time_ms: f64,
    pub success_rate: f64,
    pub coordination_latency_ms: f64,
}

/// Coordination decision context.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoordinationContext {
    pub pattern: CoordinationPattern,
    pub agent_states: Vec<AgentState>,
    pub pending_work: u32,
    pub system_metrics: serde_json::Value,
}

/// Work queue for pull-based distribution.
pub struct WorkQueue {
    items: Arc<RwLock<Vec<WorkItem>>>,
    ai_integration: Option<Arc<AIIntegration>>,
    telemetry: DefaultSwarmTelemetry,
}

/// Work item in the queue.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkItem {
    pub id: WorkId,
    pub priority: f64,
    pub requirements: Vec<String>,
    pub estimated_duration_ms: u64,
    pub created_at: SystemTime,
}

impl WorkQueue {
    pub async fn new(ai_integration: Option<Arc<AIIntegration>>) -> Result<Self> {
        Ok(Self {
            items: Arc::new(RwLock::new(Vec::new())),
            ai_integration,
            telemetry: DefaultSwarmTelemetry::default(),
        })
    }

    /// Add a work item after validating queue admission invariants.
    #[instrument(skip(self), fields(work_id = %work.id, priority = %work.priority))]
    pub async fn add_work(&self, work: WorkItem) -> Result<()> {
        if work.id.trim().is_empty() {
            bail!("work id must not be empty");
        }
        if !work.priority.is_finite() {
            bail!("work priority must be finite");
        }

        let correlation_id = CorrelationId::new();
        let _perf_timer = PerfTimer::with_correlation("work_queue_add", correlation_id.clone());
        let _span = self
            .telemetry
            .span_with_correlation("add_work_to_queue", &correlation_id)
            .entered();

        let operation_start = Instant::now();
        let mut items = self.items.write().await;

        if items.iter().any(|candidate| candidate.id == work.id) {
            bail!("work item already exists: {}", work.id);
        }

        items.push(work.clone());
        items.sort_by(|a, b| {
            b.priority
                .partial_cmp(&a.priority)
                .unwrap_or(Ordering::Equal)
        });

        let operation_duration = operation_start.elapsed();
        self.telemetry
            .record_work_item_processed(&work.id, operation_duration);
        info!(
            work_id = %work.id,
            queue_size = items.len(),
            correlation_id = %correlation_id,
            duration_us = operation_duration.as_micros(),
            "work item admitted to queue"
        );

        Ok(())
    }

    /// Get the next compatible work item.
    ///
    /// AI receives an immutable snapshot. The queue lock is never held across an
    /// external await. Any AI-selected item is revalidated while holding the
    /// write lock before it is removed.
    #[instrument(skip(self), fields(agent_id = %agent.id, agent_role = %agent.role))]
    pub async fn get_work_for_agent(&self, agent: &AgentSpec) -> Result<Option<WorkItem>> {
        let correlation_id = CorrelationId::new();
        let _perf_timer = PerfTimer::with_correlation("work_assignment", correlation_id.clone());
        let _span = self
            .telemetry
            .span_with_correlation("get_work_for_agent", &correlation_id)
            .entered();
        let operation_start = Instant::now();

        if let Some(ref ai) = self.ai_integration {
            let available_work = self.items.read().await.clone();
            if !available_work.is_empty() {
                let context = serde_json::json!({
                    "agent": agent,
                    "available_work": available_work,
                });

                let ai_start = Instant::now();
                match ai.make_decision(&context, "work_assignment").await {
                    Ok(decision) => {
                        self.telemetry.record_ai_decision(
                            "work_assignment",
                            decision.confidence,
                            ai_start.elapsed(),
                        );

                        if let Some(work_id) = decision
                            .parameters
                            .get("work_id")
                            .and_then(|value| value.as_str())
                        {
                            let mut items = self.items.write().await;
                            if let Some(position) = items.iter().position(|work| {
                                work.id == work_id && Self::agent_can_handle(agent, work)
                            }) {
                                let work_item = items.remove(position);
                                self.telemetry.record_work_item_processed(
                                    &work_item.id,
                                    operation_start.elapsed(),
                                );
                                info!(
                                    work_id = %work_item.id,
                                    agent_id = %agent.id,
                                    correlation_id = %correlation_id,
                                    "work assigned from revalidated AI selection"
                                );
                                return Ok(Some(work_item));
                            }

                            debug!(
                                requested_work_id = %work_id,
                                agent_id = %agent.id,
                                "AI selection was stale or incompatible; using deterministic fallback"
                            );
                        }
                    }
                    Err(error) => {
                        warn!(
                            agent_id = %agent.id,
                            error = %error,
                            correlation_id = %correlation_id,
                            "AI work assignment failed; using deterministic fallback"
                        );
                    }
                }
            }
        }

        let mut items = self.items.write().await;
        if let Some(position) = items
            .iter()
            .position(|work| Self::agent_can_handle(agent, work))
        {
            let work_item = items.remove(position);
            self.telemetry
                .record_work_item_processed(&work_item.id, operation_start.elapsed());
            info!(
                work_id = %work_item.id,
                agent_id = %agent.id,
                correlation_id = %correlation_id,
                "work assigned by deterministic capability matching"
            );
            return Ok(Some(work_item));
        }

        debug!(
            agent_id = %agent.id,
            available_work_count = items.len(),
            correlation_id = %correlation_id,
            "no compatible work available"
        );
        Ok(None)
    }

    fn agent_can_handle(agent: &AgentSpec, work: &WorkItem) -> bool {
        work.requirements
            .iter()
            .all(|requirement| agent.specializations.contains(requirement))
    }
}

/// Main agent coordination engine.
pub struct AgentCoordinator {
    agents: Arc<RwLock<HashMap<AgentId, AgentState>>>,
    work_queue: Arc<WorkQueue>,
    ai_integration: Option<Arc<AIIntegration>>,
    telemetry: Arc<crate::TelemetryManager>,
    coordination_lock: Arc<Mutex<()>>,
    swarm_telemetry: DefaultSwarmTelemetry,
}

impl AgentCoordinator {
    pub async fn new(
        telemetry: Arc<crate::TelemetryManager>,
        work_queue: Arc<WorkQueue>,
    ) -> Result<Self> {
        // External AI is opt-in. Core coordination must remain deterministic and
        // network-independent unless the operator explicitly enables AI.
        let ai_integration = if ai_enabled_from_env() {
            match AIIntegration::new().await {
                Ok(ai) => Some(Arc::new(ai)),
                Err(error) => {
                    warn!(error = %error, "AI integration unavailable; continuing without AI");
                    None
                }
            }
        } else {
            None
        };

        Ok(Self {
            agents: Arc::new(RwLock::new(HashMap::new())),
            work_queue,
            ai_integration,
            telemetry,
            coordination_lock: Arc::new(Mutex::new(())),
            swarm_telemetry: DefaultSwarmTelemetry::default(),
        })
    }

    pub async fn start(&self) -> Result<()> {
        info!(
            ai_enabled = self.ai_integration.is_some(),
            "agent coordinator started"
        );

        if let Some(ref ai) = self.ai_integration {
            match ai.analyze("System startup initialization").await {
                Ok(analysis) => self.swarm_telemetry.record_ai_decision(
                    "startup_analysis",
                    analysis.confidence,
                    std::time::Duration::from_millis(50),
                ),
                Err(error) => {
                    debug!(error = %error, "AI startup analysis failed");
                }
            }
        }

        Ok(())
    }

    pub async fn stop(&self) -> Result<()> {
        info!("agent coordinator stopped");
        Ok(())
    }

    /// Register an agent atomically with respect to the in-process registry.
    ///
    /// The registry critical section ends before optional AI analysis begins.
    #[instrument(skip(self), fields(agent_id = %spec.id, agent_role = ?spec.role))]
    pub async fn register_agent(&self, spec: AgentSpec) -> SwarmResult<()> {
        validate_agent_spec(&spec)?;

        let correlation_id = CorrelationId::new();
        let _perf_timer = PerfTimer::with_correlation("agent_registration", correlation_id.clone());
        let _span = self
            .swarm_telemetry
            .span_with_correlation("register_agent", &correlation_id)
            .entered();

        let lock_start = Instant::now();
        let (lock_acquisition_time, write_lock_time, agents_count) = {
            let _coordination_guard = self.coordination_lock.lock().await;
            let lock_acquisition_time = lock_start.elapsed();

            let write_start = Instant::now();
            let mut agents = self.agents.write().await;
            let write_lock_time = write_start.elapsed();

            if agents.contains_key(&spec.id) {
                return Err(SwarmError::AlreadyExists(format!(
                    "agent already registered: {}",
                    spec.id
                )));
            }

            agents.insert(
                spec.id.clone(),
                AgentState {
                    spec: spec.clone(),
                    status: AgentStatus::Active,
                    current_work: None,
                    last_heartbeat: SystemTime::now(),
                    performance_metrics: AgentMetrics {
                        work_completed: 0,
                        average_completion_time_ms: 0.0,
                        success_rate: 1.0,
                        coordination_latency_ms: 0.0,
                    },
                },
            );

            (lock_acquisition_time, write_lock_time, agents.len())
        };

        self.swarm_telemetry.record_coordination_duration(
            "agent_registration",
            lock_acquisition_time + write_lock_time,
        );
        self.swarm_telemetry.record_agent_registration(&spec.id);

        info!(
            agent_id = %spec.id,
            correlation_id = %correlation_id,
            lock_acquisition_us = lock_acquisition_time.as_micros(),
            write_lock_us = write_lock_time.as_micros(),
            agents_count,
            "agent registered"
        );

        if let Some(ref ai) = self.ai_integration {
            let context = format!(
                "New agent registered: role={}, capacity={}, specializations={:?}",
                spec.role, spec.capacity, spec.specializations
            );
            match ai.analyze(&context).await {
                Ok(analysis) => {
                    for recommendation in analysis.recommendations {
                        info!(recommendation = %recommendation, "AI registration recommendation");
                    }
                }
                Err(error) => {
                    debug!(error = %error, "AI registration analysis failed");
                }
            }
        }

        Ok(())
    }

    /// Coordinate agents using a bounded snapshot of registry state.
    #[instrument(skip(self))]
    pub async fn coordinate(&self, pattern: CoordinationPattern) -> SwarmResult<()> {
        let correlation_id = CorrelationId::new();
        let _perf_timer = PerfTimer::with_correlation(
            &format!("coordination_{pattern:?}"),
            correlation_id.clone(),
        );
        let _span = self
            .swarm_telemetry
            .span_with_correlation("coordinate_agents", &correlation_id)
            .entered();

        let lock_start = Instant::now();
        let (lock_time, read_time, agent_states) = {
            let _coordination_guard = self.coordination_lock.lock().await;
            let lock_time = lock_start.elapsed();

            let read_start = Instant::now();
            let agents = self.agents.read().await;
            let states: Vec<AgentState> = agents.values().cloned().collect();
            (lock_time, read_start.elapsed(), states)
        };

        let context = CoordinationContext {
            pattern: pattern.clone(),
            pending_work: 0,
            system_metrics: serde_json::json!({
                "total_agents": agent_states.len(),
                "active_agents": agent_states
                    .iter()
                    .filter(|agent| matches!(agent.status, AgentStatus::Active))
                    .count(),
                "working_agents": agent_states
                    .iter()
                    .filter(|agent| matches!(agent.status, AgentStatus::Working))
                    .count(),
            }),
            agent_states: agent_states.clone(),
        };

        if let Some(ref ai) = self.ai_integration {
            let analysis_context = serde_json::to_string(&context)?;
            match ai.analyze(&analysis_context).await {
                Ok(analysis) => self.apply_ai_recommendations(&analysis, &pattern).await?,
                Err(error) => {
                    debug!(error = %error, "AI coordination analysis failed");
                    self.coordinate_by_pattern(&pattern).await?;
                }
            }
        } else {
            self.coordinate_by_pattern(&pattern).await?;
        }

        self.swarm_telemetry
            .record_coordination_duration(&format!("{pattern:?}"), lock_time + read_time);

        info!(
            pattern = ?pattern,
            correlation_id = %correlation_id,
            agents_count = agent_states.len(),
            lock_time_us = lock_time.as_micros(),
            read_time_us = read_time.as_micros(),
            "agent coordination completed"
        );

        Ok(())
    }

    async fn apply_ai_recommendations(
        &self,
        analysis: &AIAnalysis,
        pattern: &CoordinationPattern,
    ) -> Result<()> {
        info!(
            recommendations = analysis.recommendations.len(),
            confidence = analysis.confidence,
            "AI coordination analysis received"
        );
        for recommendation in &analysis.recommendations {
            debug!(recommendation = %recommendation, "AI recommendation");
        }
        for opportunity in &analysis.optimization_opportunities {
            debug!(opportunity = %opportunity, "AI optimization opportunity");
        }
        self.coordinate_by_pattern(pattern).await
    }

    async fn coordinate_by_pattern(&self, pattern: &CoordinationPattern) -> Result<()> {
        match pattern {
            CoordinationPattern::ScrumAtScale => self.coordinate_scrum_at_scale().await,
            CoordinationPattern::RobertsRules => self.coordinate_roberts_rules().await,
            CoordinationPattern::Realtime => self.coordinate_realtime().await,
            CoordinationPattern::Atomic => self.coordinate_atomic().await,
        }
    }

    async fn coordinate_scrum_at_scale(&self) -> Result<()> {
        let correlation_id = CorrelationId::new();
        let _perf_timer =
            PerfTimer::with_correlation("scrum_at_scale_coordination", correlation_id.clone());

        info!(correlation_id = %correlation_id, "executing Scrum at Scale coordination");

        if let Some(ref ai) = self.ai_integration {
            let ai_start = Instant::now();
            let context = serde_json::json!({
                "coordination_type": "scrum_at_scale",
                "phase": "sprint_planning",
                "correlation_id": correlation_id.as_str(),
            });

            match ai.make_decision(&context, "sprint_planning").await {
                Ok(decision) => self.swarm_telemetry.record_ai_decision(
                    "sprint_planning",
                    decision.confidence,
                    ai_start.elapsed(),
                ),
                Err(error) => {
                    debug!(error = %error, "AI sprint planning failed");
                }
            }
        }

        Ok(())
    }

    async fn coordinate_roberts_rules(&self) -> Result<()> {
        info!("executing Roberts Rules coordination");

        if let Some(ref ai) = self.ai_integration {
            let context = serde_json::json!({
                "coordination_type": "roberts_rules",
                "phase": "motion_processing",
            });
            if let Err(error) = ai.make_decision(&context, "voting_procedure").await {
                debug!(error = %error, "AI voting procedure failed");
            }
        }

        Ok(())
    }

    async fn coordinate_realtime(&self) -> Result<()> {
        let agent_count = self.agents.read().await.len();
        info!(agent_count, "executing real-time coordination");

        if let Some(ref ai) = self.ai_integration {
            let metrics = serde_json::json!({
                "coordination_type": "realtime",
                "agent_count": agent_count,
                "timestamp": SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos(),
            });

            match ai.stream_optimizations(&metrics).await {
                Ok(mut stream) => {
                    let mut count = 0;
                    while let Some(suggestion) = stream.next().await {
                        if count >= 3 {
                            break;
                        }
                        info!(suggestion = %suggestion, "real-time AI optimization suggestion");
                        count += 1;
                    }
                }
                Err(error) => debug!(error = %error, "AI streaming failed"),
            }
        }

        Ok(())
    }

    async fn coordinate_atomic(&self) -> Result<()> {
        let coordination_epoch = SystemTime::now().duration_since(UNIX_EPOCH)?.as_nanos();
        info!(
            coordination_epoch,
            "executing bounded in-process atomic coordination"
        );
        Ok(())
    }

    pub async fn get_ai_recommendations(
        &self,
        pattern: &CoordinationPattern,
    ) -> Result<AIAnalysis> {
        if let Some(ref ai) = self.ai_integration {
            let context = format!("Analyze coordination pattern: {}", pattern.description());
            ai.analyze(&context).await
        } else {
            bail!("AI integration is not enabled")
        }
    }

    pub async fn optimize_work_distribution(&self) -> Result<()> {
        if let Some(ref ai) = self.ai_integration {
            let specializations: Vec<String> = {
                let agents = self.agents.read().await;
                agents
                    .values()
                    .flat_map(|agent| agent.spec.specializations.clone())
                    .collect()
            };

            match ai.get_pattern_embeddings(specializations).await {
                Ok(embeddings) => {
                    info!(
                        embeddings = embeddings.len(),
                        "generated embeddings for work optimization"
                    );
                }
                Err(error) => debug!(error = %error, "embedding generation failed"),
            }
        }

        Ok(())
    }

    /// Number of currently registered agents.
    pub async fn agent_count(&self) -> usize {
        self.agents.read().await.len()
    }

    /// Whether optional AI coordination is enabled for this coordinator.
    pub fn ai_enabled(&self) -> bool {
        self.ai_integration.is_some()
    }

    /// Return the work queue used by this coordinator.
    pub fn work_queue(&self) -> &Arc<WorkQueue> {
        &self.work_queue
    }

    /// Return the telemetry manager used by this coordinator.
    pub fn telemetry(&self) -> &Arc<crate::TelemetryManager> {
        &self.telemetry
    }
}

fn ai_enabled_from_env() -> bool {
    std::env::var("SWARMSH_ENABLE_AI")
        .map(|value| {
            matches!(
                value.to_ascii_lowercase().as_str(),
                "1" | "true" | "yes" | "on"
            )
        })
        .unwrap_or(false)
}

fn validate_agent_spec(spec: &AgentSpec) -> SwarmResult<()> {
    if spec.id.trim().is_empty() {
        return Err(SwarmError::Coordination(
            "agent id must not be empty".to_string(),
        ));
    }
    if spec.role.trim().is_empty() {
        return Err(SwarmError::Coordination(
            "agent role must not be empty".to_string(),
        ));
    }
    if !spec.capacity.is_finite() || spec.capacity <= 0.0 {
        return Err(SwarmError::Coordination(
            "agent capacity must be finite and greater than zero".to_string(),
        ));
    }
    if spec.work_capacity == Some(0) {
        return Err(SwarmError::Coordination(
            "agent work capacity must be greater than zero when specified".to_string(),
        ));
    }
    Ok(())
}
